name: Build And Publish

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version (e.g., 2.0.0)'
        required: true
      build_type:
        type: choice
        description: 'Build configuration'
        required: true
        options:
          - Release
          - Debug

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          cache: true
          cache-dependency-path: 'packages.lock.json'

      - name: Restore dependencies
        run: dotnet restore FikaHeadlessManager.csproj

      - name: Publish Windows build
        run: dotnet publish FikaHeadlessManager.csproj --configuration ${{ inputs.build_type }} --no-restore --runtime win-x64 --output output/windows/ -p:PublishSingleFile=true -p:SelfContained=false -p:DebugType=None -p:DebugSymbols=false -p:PublishTrimmed=false -p:Version=${{ inputs.release_version }} -p:AssemblyVersion=${{ inputs.release_version }} -p:FileVersion=${{ inputs.release_version }} -p:InformationalVersion=${{ inputs.release_version }}

      - name: Copy license
        run: Copy-Item LICENSE.md output/windows/FikaHeadlessManager-LICENSE.md

      - name: Zip Windows build
        run: Compress-Archive -Path "output/windows/*" -DestinationPath "Fika Headless Manager ${{ inputs.release_version }}.zip"

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: Fika Headless Manager ${{ inputs.release_version }}
          path: Fika Headless Manager ${{ inputs.release_version }}.zip

  release:
    needs: [build-windows]
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: releases

      - name: Create GitHub Release Draft
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ inputs.release_version }}
          name: Fika Headless Manager ${{ inputs.release_version }}
          draft: true
          files: releases/**/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
